version: '3.7'

services:
    currency-exchange:
      image: shashitale/exchange-service
      mem_limit: 800m 
      ports:
       - "8000:8000"
      depends_on:
        - aws-ot-collector
      environment:
        OTEL_EXPORTER_OTLP_ENDPOINT : http://aws-ot-collector:4317
        OTEL_TRACES_EXPORTER : otlp
        OTEL_METRICS_EXPORTER : prometheus        
        SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:29092
        EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      extra_hosts:
        - "host.docker.internal:host-gateway"

    currency-conversion:
      image: shashitale/currency-conversion
      mem_limit: 700m
      ports:
       - "8100:8100"
      depends_on:
        - naming-server
      environment:
        OTEL_EXPORTER_OTLP_ENDPOINT : http://aws-ot-collector:4317
        OTEL_TRACES_EXPORTER : otlp
        OTEL_METRICS_EXPORTER : prometheus
        SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:29092
        EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka 
      extra_hosts:
        - "host.docker.internal:host-gateway"

    kafka-service2:
      image: shashitale/kafka-service2
      mem_limit: 700m
      ports:
       - "8300:8300"
      depends_on:
        - naming-server
      environment:
        OTEL_EXPORTER_OTLP_ENDPOINT : http://aws-ot-collector:4317
        OTEL_TRACES_EXPORTER : otlp      
        SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:29092
        EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
          
    kafka-service1:
      image: shashitale/kafka-service1
      mem_limit: 700m
      ports:
       - "8200:8200"
      depends_on:
        - naming-server
      environment:
        OTEL_EXPORTER_OTLP_ENDPOINT : http://aws-ot-collector:4317
        OTEL_TRACES_EXPORTER : otlp
        SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:29092
        EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka

    
    api-gateway:
      image: shashitale/api-gateway
      mem_limit: 700m 
      ports:
       - "8765:8765"
      depends_on:
        - naming-server
      environment:
        OTEL_EXPORTER_OTLP_ENDPOINT : http://aws-ot-collector:4317
        OTEL_TRACES_EXPORTER : otlp      
        SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:29092
        EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
        
      # ADOT Collector
    aws-ot-collector:   
      image: amazon/aws-otel-collector:latest
      command: ["--config=/etc/otel-agent-config.yaml"]    
      ports:
        - "1777:1777"   # pprof extension
        - "55679:55679" # zpages extension
        - "13133"
        - "4317"
        - "4318"
      environment:
        - AWS_ACCESS_KEY_ID=AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY=AWS_SECRET_ACCESS_KEY
        - AWS_REGION=AWS_REGION
      volumes:
        - ./config-test.yaml:/etc/otel-agent-config.yaml
    
    naming-server:
      image: shivamec92/mmv2-naming-server:0.0.1-SNAPSHOT
      mem_limit: 700m
      ports:
       - "8761:8761"