version: '3.7'

services:
    currency-exchange:
      image: shivamec92/mmv2-currency-exchange-service:0.0.1-SNAPSHOT
      mem_limit: 800m
      volumes:
        - ./otel-jar/aws-opentelemetry-agent.jar:/aws-opentelemetry-agent.jar 
      ports:
       - "8000:8000"
      networks:
        - currency-network
      depends_on:
        - naming-server
      environment:
        SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:29092
        EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
        SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
        JAVA_OPTS: "$JAVA_OPTS -javaagent:/aws-opentelemetry-agent.jar -Dotel.resource.attributes=service.name=CurrencyExchange 
          -Dotel.exporter=otlp -Dotel.exporter.otlp.endpoint=http://host.docker.internal:4317"
      extra_hosts:
        - "host.docker.internal:host-gateway"

      
    currency-conversion:
      image: shivamec92/mmv2-currency-conversion-service:0.0.1-SNAPSHOT
      mem_limit: 700m
      volumes:
        - ./otel-jar/aws-opentelemetry-agent.jar:/aws-opentelemetry-agent.jar 
      ports:
       - "8100:8100"
      networks:
        - currency-network
      depends_on:
        - naming-server
      environment:
        SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:29092
        EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
        SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
        JAVA_OPTS: "$JAVA_OPTS -javaagent:/aws-opentelemetry-agent.jar -Dotel.resource.attributes=service.name=CurrencyConversion 
          -Dotel.exporter=otlp -Dotel.exporter.otlp.endpoint=http://host.docker.internal:4317"
    
    log-request-chain:
      image: shivamec92/mmv2-log-request-chain:0.0.1-SNAPSHOT
      mem_limit: 700m
      volumes:
        - ./otel-jar/aws-opentelemetry-agent.jar:/aws-opentelemetry-agent.jar 
      ports:
       - "8004:8004"
      networks:
        - currency-network
      depends_on:
        - naming-server
      environment:
        SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:29092
        EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
        SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
        JAVA_OPTS: "$JAVA_OPTS -javaagent:/aws-opentelemetry-agent.jar -Dotel.resource.attributes=service.name=LogRequestChain 
          -Dotel.exporter=otlp -Dotel.exporter.otlp.endpoint=http://host.docker.internal:4317"
          
    log-requests:
      image: shivamec92/mmv2-log-requests:0.0.1-SNAPSHOT
      mem_limit: 700m
      volumes:
        - ./otel-jar/aws-opentelemetry-agent.jar:/aws-opentelemetry-agent.jar 
      ports:
       - "8003:8003"
      networks:
        - currency-network
      depends_on:
        - naming-server
      environment:
        SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:29092
        EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
        SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
        JAVA_OPTS: "$JAVA_OPTS -javaagent:/aws-opentelemetry-agent.jar -Dotel.resource.attributes=service.name=LogRequest 
          -Dotel.exporter=otlp -Dotel.exporter.otlp.endpoint=http://host.docker.internal:4317"
    
    api-gateway:
      image: shivamec92/mmv2-api-gateway:0.0.1-SNAPSHOT
      mem_limit: 700m
      volumes:
        - ./otel-jar/aws-opentelemetry-agent.jar:/aws-opentelemetry-agent.jar 
      ports:
       - "8765:8765"
      networks:
        - currency-network
      depends_on:
        - naming-server
      environment:
        SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:29092
        EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
        SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
        JAVA_OPTS: "$JAVA_OPTS -javaagent:/aws-opentelemetry-agent.jar -Dotel.resource.attributes=service.name=APIGateway 
          -Dotel.exporter=otlp -Dotel.exporter.otlp.endpoint=http://host.docker.internal:4317"
     
    naming-server:
      image: shivamec92/mmv2-naming-server:0.0.1-SNAPSHOT
      mem_limit: 700m
      ports:
       - "8761:8761"
      networks:
        - currency-network
        
    zipkin-server:
      image: openzipkin/zipkin:2.23
      mem_limit: 700m
      ports:
       - "9411:9411"
      networks:
        - currency-network
        
networks:
  currency-network: